"""Moving is_activate to user table

Revision ID: 12424eba52b5
Revises: fc9da4c3e4ba
Create Date: 2022-09-18 01:16:38.514202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12424eba52b5'
down_revision = 'fc9da4c3e4ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_active')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
